const SCREEN = {
  SPLASH: 'Splash',
  ON_BOARDING: 'OnBoarding',
};

const EVENT_FLOW_SCREENS = {
  EVENT_REGISTRATION: 'EventRegistration',
  EVENT_PAYMENT: 'EventPayment',
  EVENT_CONFIRMATION: 'EventConfirmation',
  EVENT_RECEIPT: 'EventReceipt',
};

const STACKS = {
  STACK_NAVIGATOR: "StackNavigator",
  BOTTOM_TAB: "Tab Navigator",
  EVENTS_STACK: "Event",
  EVENT_REGISTRATION: EVENT_FLOW_SCREENS.EVENT_REGISTRATION,
  EVENT_PAYMENT: EVENT_FLOW_SCREENS.EVENT_PAYMENT,
  EVENT_CONFIRMATION: EVENT_FLOW_SCREENS.EVENT_CONFIRMATION,
  EVENT_RECEIPT: EVENT_FLOW_SCREENS.EVENT_RECEIPT,
  CATEGORIES_STACK: "Categories",
  APPLICATION_STACK: "Application",
  APPLICATION_HISTORY: "ApplicationHistory",
  APPLICATION_DETAIL: "ApplicationDetail",
  APPLICATION_FORM: "ApplicationForm",
  DASHBOARD_STACK: "Dashboard",
  COURSES_STACK: "Courses",
  MEMBERSHIP_STACK: "Membership",
  PAYMENT_STACK: "Payment",
  PAYMENT_METHOD_STACK: "PaymentMethod",
  QUERIES_CASES_STACK: "QueriesCases",
  CREATE_CASE: "CreateCase",
};

const TAB = {
  EXPLORE: 'Explore',
  LOCAL: 'Nearby',
};
export { SCREEN, TAB, STACKS, EVENT_FLOW_SCREENS }