import { Platform, StyleSheet } from 'react-native';
const transparentStatus = {
  statusBarTranslucent: true,
  statusBarColor: transparent,
};
const statusBarColor = '#218FB1';
const primaryColor = '#000000';
const secondryColor = '#FFFFFF';
const tertiaryColor = '#99999B';
const btnBG = '#565658';
const textColor = '#FFFFFF';
const textColorDim = '#BBBBBB';
const transparent = 'transparent';
const white = '#FFFFFF';
const dimPrimaryColor = '#464648';

const normalFont = Platform.OS === 'ios' ? 'Inter-Regular' : 'Inter-Regular';
const mediumFont = Platform.OS === 'ios' ? 'Inter-Medium' : 'Inter-Medium';
const semiBoldFont =
  Platform.OS === 'ios' ? 'Inter-SemiBold' : 'Inter-SemiBold';
const boldFont = Platform.OS === 'ios' ? 'Inter-Bold' : 'Inter-Bold';
const styleFont =
  Platform.OS === 'ios' ? 'RobotoFlex-Regular' : 'RobotoFlex-Regular';
const textFont = { fontFamily: normalFont };
const mediumTextFont = { fontFamily: mediumFont };
const semiTextFont = { fontFamily: semiBoldFont };
const boldTextFont = { fontFamily: boldFont };
const styleTextFont = { fontFamily: styleFont };
const container = StyleSheet.create({
  parent: {
    flex: 1,
    backgroundColor: '#000',
  },
  scrollView: {
    flexGrow: 1,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#000',
  },
  empty: { flex: 1, backgroundColor: primaryColor },
  roundFormBG: {
    flex: 1,
    paddingVertical: 30,
    borderTopStartRadius: 30,
    borderTopEndRadius: 30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: -20,
  },
});
const Colors = {
  primary: '#0A84FF',
  white: '#FFFFFF',
  grey70: '#48484A',
  gray: '#929292',
  lightgrey: '#F4F4F4',
  grey700: '#AEAEB2',
  ligthWhite: '#f8f8f8',
  darkgrey: '#363638',
  orange: '#F48120',
  golden: '#FFD213',
  dodgeBlue: '#2196F3',
  fruitSalad: '#4CAF50',
  black: '#000000',
  Ruby: '#E91E63',
  grey300: '#C7C7CC',
  lightYellow: '#FFC107',
  NeroBlack: '#1D1D1D',
  backFaded: 'rgba(255, 255, 255, 0.2)',
  lightsky: '#D4FFF2',
  Green: '#41AD49',
  orangePeel: '#FF9800',
  lightGreen: '#F5FFFC',
  redFaded: 'rgba(255,0,0,0.4)',
  red: 'rgb(155,0,0)',
  iconColor: '#949494',
  StarkWhite: '#CCC4B7',
  appleBlue: '#559EF8',
  Manatee: '#86868A',
  darkCharcoal: '#323234', //Divider Color
  Charcoal: '#323233',
  charlestonGreen: '#2C2C2E',
  gray9: '#171717',
  frenchGray: '#C7C7CB',
  Gray60: '#99999B',
  GreySuit: '#8E8E92',
  TricornBlack: '#2C2C2D',
  gray97: '#7F7F7F',
  JetBlack: '#323233',
  PayneGrey: '#464648',
  PictonBlue: '#4293EE',
  ChestyBond: '#526E9F',
  davyGrey: '#555555',
  gray15: '#262626',
  gray75: '#BFBFBF',
  gingerBlue: '#559EF8',
  redOrange: '#FF2222',
  pinkSwan: '#B2B2B2',
  eclipse: '#363637',
  SpanishGray: '#989898',
  GunPowder: '#575759',
  Alabaster: '#FAFAFA',
  Gray22: '#383838',
  SpanishGray99: '#98979C',
  RaisanBlack: '#282829',
  silver: '#C5C5C5',
  Gray88: '#E0E0E0',
  dullBlack: '#161616',
  pureBlue: '#0095F6',
  lightishBlue: '#3F86F7',
  congressBlue: '#64B1F9',
  seaGreen: '#4F9289',
  deepOrange: '#EA8634',
  aluminium: '#8A8A8D',
  Pantone: '#5A5F65',
  PantoneC: '#89898D',
  Magenta: '#5E5E5F',
  blackRussian: '#1C1C1D',
  blackRussian1: '#1C1C1E',
  Gray35: '#59595D',
  lightSilver: '#CBCBD0',
  grey500: '#8E8E93',
  grey600: '#636366',
  halfWhite: '#F8F8FF',
  dimGray: '#C6C6CC',
  Smokey: '#646467',
  santasGray: '#9D9DA6',
  Azure: '#9B9CA2',
  extraSilver: '#C4C4C4',
  cyanBlue: '#0095F6',
  RaisinBlack: '#202022',
  SuvaGrey: '#929296',
  CharcoalGray: '#564E46',
  StonewallGrey: '#C1C1C1',
  NightRider: '#303030',
  dimWhite: '#F2F2F2',
  MediumSilver: '#B9B9B9',
  Blue: '#3A82F7',
  Gray66: '#A8A8A8',
  MidGray: '#656569',
  SlateGray: '#98989E',
  darkCharcoal2: '#333434',
  brightRed: '#EB4D3D',
  Gray24: '#3D3D3D',
  LoveRed: '#E41F17',
  Gray59: '#969696',
  StormGray: '#787A7D',
  grey900: '#2D2C2E',
  searchFaded: 'rgba(255,255,255,0.25)',
  silvedFaded: 'rgba(196, 196, 196, 0.7)',
  whiteFaded: 'rgba(255, 255, 255, 0)',
  backdrop: 'rgba(0, 0, 0, 0.4)',
  blurEffect: 'rgba(0, 0, 0, 0.5)',
  blackShadow: '#rgba(0, 0, 0, 0.6)',
  blackFaded: 'rgba(0, 0, 0, 0.7)',
  blackOpaque: 'rgba(0, 0, 0, 0.9)',
  fadedBlack: 'rgba(0, 0, 0, 0)',
  naturalGrey: '#F2F2F7',
  grey950: '#1C1B1D',
  grey800: '#3A3A3C',
  red50: '#FF443A',
  grey50: '#F2F2F7',
  blue100: '#4293EE',
  blue200:'#0A84FF'
};

const headings = StyleSheet.create({
  h0M: { ...mediumTextFont, fontSize: 45 },
  h0s: { ...semiTextFont, fontSize: 33, color: textColor },
  h1b: { ...textFont, fontSize: 30, color: textColor },
  h1s: { ...styleTextFont, fontSize: 28, color: textColor, fontWeight: 'bold' },
  h1SB: { ...styleTextFont, fontSize: 16, color: textColor, fontWeight: 'bold' },
  h1SS: { ...styleTextFont, fontSize: 16, color: textColor, fontWeight: '400' },
  h1: { ...semiTextFont, fontSize: 28, color: textColor },
  h1S: { ...semiTextFont, fontSize: 26, color: textColor },
  h2: { ...mediumTextFont, fontSize: 24, color: textColor },
  h2M: { ...semiTextFont, fontSize: 24, color: textColor },
  h2s: { ...textFont, fontSize: 25, color: Colors.Azure },
  h3: { ...mediumTextFont, fontSize: 22, color: textColor },
  h3SB: { ...semiTextFont, fontSize: 22, color: textColor },
  h3F: { ...mediumTextFont, fontSize: 22 },
  h3b: { ...boldTextFont, fontSize: 22, color: textColor },
  h3n: { ...textFont, fontSize: 22, color: textColor },
  h3S: { ...boldTextFont, fontSize: 22, color: primaryColor },
  h4: { ...mediumTextFont, fontSize: 20, color: textColor },
  h4b: { ...boldTextFont, fontSize: 36, color: textColor },
  h4S: { ...semiTextFont, fontSize: 32, color: textColor },
  h5: { ...textFont, fontSize: 18, color: textColor },
  h5b: { ...boldTextFont, fontSize: 32, color: textColor },
  h5SB: { ...semiTextFont, fontSize: 38, color: textColor },
  h5M: { ...mediumTextFont, fontSize: 18, color: textColor },
  h5S: { ...semiTextFont, fontSize: 18, color: textColor },
  h6: { ...textFont, fontSize: 16, color: textColor },
  h6M: { ...semiTextFont, fontSize: 16, color: textColor },
  h6B: { ...boldTextFont, fontSize: 16, color: textColor },
  h7: { ...semiTextFont, fontSize: 17, color: textColor },
  h7M: { ...semiTextFont, fontSize: 17, color: primaryColor },
  h7B: { ...boldTextFont, fontSize: 17, color: textColor },
  h8: { ...textFont, fontSize: 15, color: textColor },
  h8M: { ...semiTextFont, fontSize: 15, color: textColor },
  h8S: { ...mediumTextFont, fontSize: 15, color: Colors.MediumSilver },
  h8B: { ...boldTextFont, fontSize: 15, color: textColor },
  h9: { ...textFont, fontSize: 12.5, fontWeight: '400', color: primaryColor },
  H9M: {
    ...semiTextFont,
    fontSize: 12.5,
    fontWeight: '600',
    color: Colors.frenchGray,
  },
  H9S: { ...mediumTextFont, fontSize: 13, fontWeight: '500', color: textColor },
  H9B: { ...semiTextFont, fontSize: 13, fontWeight: '600', color: textColor },
  H9SB: { ...boldTextFont, fontSize: 13, fontWeight: '700', color: textColor },
  h10: { ...textFont, fontSize: 17, fontWeight: '400', color: Colors.Blue },
  H11M: {
    ...mediumTextFont,
    fontSize: 17,
    fontWeight: '500',
    color: Colors.gingerBlue,
  },
  H11MW: { ...mediumTextFont, fontSize: 17, fontWeight: '500', color: textColor },
  H11: {
    ...mediumTextFont,
    fontSize: 11,
    fontWeight: '500',
    color: Colors.SpanishGray99,
  },
  H12: { ...textFont, fontSize: 14, fontWeight: '400', color: Colors.Azure },
  H12B: { ...boldTextFont, fontSize: 12, fontWeight: '700', color: textColor },
  H12M: { ...mediumTextFont, fontSize: 12, fontWeight: '500', color: textColor },
  H13S: { ...semiTextFont, fontSize: 10, fontWeight: '600', color: textColor },
  H13M: { ...mediumTextFont, fontSize: 10, fontWeight: '500', color: textColor },
  H13: { ...textFont, fontSize: 10, fontWeight: '400', color: textColor },
  H14: { ...textFont, fontSize: 11, fontWeight: '400', color: textColor },
  H14S: { ...semiTextFont, fontSize: 11, fontWeight: '600', color: textColor },
  H14M: { ...mediumTextFont, fontSize: 11, fontWeight: '500', color: textColor },
  H15M: { ...mediumTextFont, fontSize: 9, fontWeight: '500', color: textColor },
  H15: { ...textFont, fontSize: 9, fontWeight: '500', color: textColor },
  H15B: { ...boldTextFont, fontSize: 9, fontWeight: '700', color: textColor },
  h10SS: { ...styleTextFont, fontSize: 12, color: textColor, fontWeight: '400' },
  h13SS: { ...styleTextFont, fontSize: 13, color: textColor, fontWeight: '400' },
  h22SS: { ...semiTextFont, fontSize: 21, color: textColor },
});

const form = StyleSheet.create({
  inputBG: {
    flexDirection: 'row',
    borderRadius: 20,
    marginVertical: 10,
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  inputText: {
    ...semiTextFont,
    paddingStart: 10,
    flex: 1,
    fontSize: 15,
    color: textColor,
  },
  inputStyle: { ...headings.h4b, paddingStart: 10, flex: 1, textAlign: 'center' },
  inputTextStyle: {
    ...mediumTextFont,
    fontSize: 17,
    fontWeight: '500',
    color: Colors.MidGray,
  },
  normalInputStyle: {
    ...textFont,
    fontSize: 15,
    fontWeight: '400',
    color: Colors.Gray66,
  },
});

const shadow = StyleSheet.create({
  whiteShadow: {
    shadowColor: primaryColor,
    shadowColor: primaryColor,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
});
const btnStyle = StyleSheet.create({
  btnBG: {
    backgroundColor: btnBG,
    height: 50,
    paddingHorizontal: 20,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  btnText: {
    ...semiTextFont,
    fontSize: 17,
    color: primaryColor,
  },
});

export {
  transparentStatus,
  textFont,
  semiTextFont,
  boldTextFont,
  mediumFont,
  textColorDim,
  btnStyle,
  statusBarColor,
  dimPrimaryColor,
  btnBG,
  white,
  textColor,
  mediumTextFont,
  styleTextFont,
  container,
  primaryColor,
  secondryColor,
  tertiaryColor,
  headings,
  form,
  shadow,
  transparent,
  Colors,
};
